include(CheckCXXCompilerFlag)

# Compiler checks
message(STATUS "Checking compiler flags support")
set(CMAKE_MESSAGE_CONTEXT "compiler checks")
check_cxx_compiler_flag("-g3" CXX_ACCEPTS_G3)
check_cxx_compiler_flag("-g" CXX_ACCEPTS_G)
check_cxx_compiler_flag("-Og" CXX_ACCEPTS_OG)
check_cxx_compiler_flag("-march=native" CXX_ACCEPTS_MARCH_NATIVE)

if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    check_cxx_compiler_flag("-flto=thin" CXX_ACCEPTS_THIN_LTO)
    check_cxx_compiler_flag("-fwhole-program-vtables" CXX_ACCEPTS_WHPR_VTABLE)
    check_cxx_compiler_flag("-fstrict-vtable-pointers" CXX_ACCEPTS_STRICT_VTABLE)
else()
    check_cxx_compiler_flag("-flto" CXX_ACCEPTS_FLTO)
    check_cxx_compiler_flag("-fwhole-program" CXX_ACCEPTS_WHLP)
    check_cxx_compiler_flag("-fuse-linker-plugin" CXX_ACCEPTS_LINKER_PLUGIN)
endif()

set(CMAKE_MESSAGE_CONTEXT "")

if(CXX_ACCEPTS_G3)
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g3")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_DEBUG} -g3")
elseif(CXX_ACCEPTS_G)
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g")
    set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_DEBUG} -g")
endif()

if(CXX_ACCEPTS_OG)
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Og")
else()
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O1")
endif()

if(CMAKE_CXX_COMPILER_ID MATCHES ".*Clang")
    if(CXX_ACCEPTS_THIN_LTO)
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -flto=thin")
        set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -flto=thin")
    endif()
    if(CXX_ACCEPTS_WHPR_VTABLE)
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -fwhole-program-vtables")
    endif()
    if(CXX_ACCEPTS_STRICT_VTABLE)
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -fstrict-vtable-pointers")
    endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(CXX_ACCEPTS_FLTO)
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -flto")
        set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -flto")
    endif()
    if(CXX_ACCEPTS_WHLP)
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -fwhole-program")
    endif()
    if(CXX_ACCEPTS_LINKER_PLUGIN)
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -fuse-linker-plugin")
    endif()
endif()

if(OPTIMIZE_FOR_NATIVE_MICROARCH AND CXX_ACCEPTS_MARCH_NATIVE)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native")
endif()
